Dualclock fifos
TUM-LIS/glip pull request #59
Opened 2018-04-30 14:02 UTC by koenenwmn

Added the new dualclock FIFOs with programmable full and empty flags, renamed the singleclock FIFOs, fixed a bug in the FX3 toplevel and adjusted the demo projects.
I tested the VCU108 demo projects and they work. I didn't test the projects for the other boards though.
@imphil and @wallento , please have a look and let me know if this works for you or if you need me to change anything.

2018-04-30 14:20 UTC, imphil requested changes
Very nice work @koenenwmn . I've looked through it and mentioned a couple smaller things, but overall I trust your testing.

Before we merge this one, could you
- Address my comments (or dismiss them if they don't make sense)
- Test the UART backend on the Nexys4 DDR board. This is the most common backend in OpTiMSoC and we don't want to break this one.
- You wrote tests for this code with cocotb, didn't you? If so, could you add them to the commit as well, so that we have in GLIP essentially a full copy of the fifo directory as it (will be) in OpTiMSoC. This should make it easier to sync changes between the two projects.

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx2/logic/demo/ztex_115_loopback/loopback_synplify.prj
> +add_file -systemverilog "../../../../common/logic/fifo/verilog/fifo_dualclock_standard.sv"
According to https://www.microsemi.com/document-portal/doc_view/134093-synopsys-fpga-synthesis-i-2013-09m-sp1-1-command-reference-manual this should be "-verilog" instead of "-systemverilog"

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx2/logic/demo/ztex_213_loopback/loopback_synplify.prj
> +add_file -systemverilog "../../../../common/logic/fifo/verilog/fifo_dualclock_standard.sv"
same as above

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx2/logic/verilog/glip_cypressfx2_toplevel.v
> +      .DEPTH(16))
The FIFOs in here had a depth of 4 when using the cdc_fifo module? If so, can we keep that value for the new FIFOs as well?

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx2/logic/verilog/glip_cypressfx2_toplevel.v
> +      .DEPTH(16))
Some comment as above for the DEPTH.

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx3/logic/demo/vcu108_stress_test/vcu108_fx3_stress_test.v
> +/* Copyright (c) 2018 by the author(s)
2017-2018 that should be

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx3/logic/demo/vcu108_stress_test/vcu108_fx3_stress_test.v
> +      .clk_in(clk_in_clk_wiz_0),
nit: indentation

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx3/logic/demo/vcu108_stress_test/vcu108_fx3_stress_test.v
> +   wire clk_in_clk_wiz_0;
please use a more descriptive name for this wire.

2018-04-30 14:20 UTC, imphil commented on src/backend_cypressfx3/logic/demo/vcu108_stress_test/vcu108_stress_test_clock.v
>     wire        clk_out1_clk_wiz_0;
while being at it, you might also want to rename this one to be more descriptive.

2018-04-30 14:20 UTC, imphil commented on src/backend_uart/logic/verilog/glip_uart_toplevel.v
> +      .DEPTH(8))
Same as before: the cdc_fifo had IIRC a depth of 4 by default; please use the same depth if possible to keep the behavior the same.

2018-05-03 07:38 UTC, koenenwmn commented on src/backend_cypressfx2/logic/verilog/glip_cypressfx2_toplevel.v
> +      .DEPTH(16))
Actually, the cdc FIFO uses ADDRSIZE (which defaults to 4) as parameter instead of DEPTH. The depth of the two should hence be the same, or am I making a mistake here?

2018-05-03 07:39 UTC, koenenwmn commented on src/backend_cypressfx2/logic/verilog/glip_cypressfx2_toplevel.v
> +      .DEPTH(16))
Same here.

2018-05-03 08:00 UTC, imphil commented on src/backend_cypressfx2/logic/verilog/glip_cypressfx2_toplevel.v
> +      .DEPTH(16))
ah ok, then it's fine.

2018-05-04 09:35 UTC, merged

2018-05-04 09:36 UTC, imphil commented
Thanks @koenenwmn for pushing this through. Next up: update_externals in optimsoc and an update of the fifos in optimsoc to keep things consistent.