Channel multiplexer
TUM-LIS/glip pull request #61
Opened 2018-07-05 09:11 UTC by yaorong0921

This is the first draft of channel multiplexer module.

2018-07-05 09:39 UTC, imphil commented
@yaorong0921 , thanks for this PR. Before we go into the details, please fix two things:

- Change your editor configuration to remove all tabs and indent Verilog code with three spaces.
- Do not commit *.pyc files, only *.py files.

Please update this PR by making the required changes and pushing into the same branch as before (yaorong0921:channel_multiplexer). The PR will then update automatically.

2018-07-05 10:15 UTC, yaorong0921 commented
@imphil I am sorry, but I tried to commit again with required edit config, but it still looks strange in the commit file. It looks nice in my local file . I am not sure what I did wrong in my commit here. 
I only did :1. git commit ; 2. git push

Thank you!

2018-07-05 11:27 UTC, imphil commented
Then you probably forgot git add. Please use git status to see what's going on. (If this all sounds strange to you, please take the time to do a git tutorial.)

2018-07-05 13:34 UTC, imphil requested changes
The code formatting is not yet where it could be. I've marked a couple points in the code, please apply them consistently through the whole file. Look through the whole changeset and take greatest care on all the details! 

Additionally, please remove the *.pyc files from the commit using `git rm`.

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +   parameter CHANN =8
`CHANN = 8`

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +   input[CHANN-1:0]        fifo_rd_en_channel_ingress ,
`input [CHANN-1:0]` (space!)
`fifo_rd_en_channel_ingress,` (no space before comma)

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +   //Memory storing input/output to each fifo for each channel (ingress)
`// Memory` (space after comment)

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +   reg  [CHANN-1:0]            fifo_wr_en_channel_ingress ;
`reg [CHANN-1:0]` (only one space after `reg`)
`fifo_wr_en_channel_ingress;` (no space before `;`)

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +            fifo_channel_ingress(
be consistent. Either `PARAMETER(VALUE)` or `PARAMETER (VALUE)`

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +	    #(.WIDTH (8),
have consistent 3-space indentation, line 101 has three spaces, line 102 has two spaces.

2018-07-05 13:34 UTC, imphil commented on src/common/logic/channel_multiplexing/channel_multiplexer.sv
> +      end
Please take a close look at this block and make the indentation consistent.

2018-07-05 13:52 UTC, imphil commented
Please make use of your editor's feature to search for tabs (typically search for `\t` using regex or escape sequence mode) and get rid of all of them.

2018-07-06 09:00 UTC, imphil requested changes
Thanks for fixing the code style, the PR is now much easier to read -- which allows us to proceed to my comments on the content.

- Is there any connection between egress and ingress path? If there is not (and I didn't see any) you can split this code into two modules. (Which also means two files.) Possibly a channel multiplexer and demultiplexer are the right names?
- Don't mix blocking and non-blocking assignments in Verilog. Use non-blocking assignments (`<=`) in sequential blocks (`always @ posedge(clk)`), and blocking assignments (`=`) in combinatorial blocks (`always @(*)`).
- Do not use the `integer` data type in code that is synthesized (except for `generate` blocks). Integers will be synthesized to 32 bit wide data busses, which is typically not what you're looking for.
- A small style thing: prefix all module instances with `u_`, e.g. `u_fifo_channel_ingress`.

Once these things are fixed you can go ahead and write cocotb test(s) for your module. I'm sure you'll uncover some more things, and once you're happy with the result we can have another look at the code.

2018-07-18 10:31 UTC, yaorong0921 commented
@imphil Hi, i have the question about the integer.  I used integer `channel_number`, because i want to give the value to different element in array (like in generate block `i`). So in this case, is it proper to use integer? If not, what should i then turn to if i want to give the value to array? Thank you very much!

2018-07-18 10:58 UTC, koenenwmn commented
In that case you should use a register with a width that is just big enough to hold the (binary) number of channels that you want to address. SystemVerilog provides a function for that: `$clog2(CHANN)`
So you could create a register like this:
`reg [$clog2(CHANN)-1:0] channel_number;`

2018-08-02 08:09 UTC, koenenwmn requested changes
Thanks for the commit. I added some remarks, mainly to the tests.
In general, I would ask you to extend your current tests to general stress tests where the write and read threads run concurrently for a couple thousand cycles, so we can test things like back pressure.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_demultiplexer_test.manifest.yaml
> +  - /home/ga84bif/optimsoc/glip/src/common/logic/fifo/verilog/fifo_dualclock_fwft.sv
Please use relative paths to the sources (also in the other manifest).

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_demultiplexer_test.manifest.yaml
> +
Please avoid spaces in empty lines or at the end of a file (there are also a couple of other occasions).

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_demultiplexer_test.py
> +
Just a formatting thing: Try and avoid empty lines in the description text if not necessary, but add one afterwards, to be consistent with the rest of the project.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_demultiplexer_test.py
> +    for _ in range(1):
It's always a good idea to have the reset signal assigned for at least 2 cycles.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_demultiplexer_test.py
> +    yield write_thread.join()
This is a good start for testing a single write/read cycle. It should be extended though, to really perform a stress test on the DUT, meaning both threads should run in parallel and write to/read from the device concurrently (same for the multiplexer test).

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +        # make sure that the full signal is stable before checking for it
You never actually check the full signal before writing to the DUT. This only works as long as you don't write more words than what fits in the buffer.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +                # send control word again
There should be a 'yield' in between here, otherwise you just overwrite the first assignment to the DUT in the same cycle. Also, if writing two words, you would also have to increase your 'fifo_wrcnt' twice.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +            # deactivate read request if we have wait cycles
If you have a read delay here, you should also clear 'fifo_rd_en_channel'.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +        yield FallingEdge(clk[channel_count])
Try to consistently yield either falling edges or rising edges, otherwise it get's confusing.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +            if ~dut.fifo_empty_channel[channel_count].value:
`!dut.fifo_empty_channel[channel_count].value.integer`

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +            fifo_rdcnt += 1
I guess this should be reset when you switch to the next channel?

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +        # make sure that the full signal is stable before checking for it
Same thing, you should actually check the full signal before writing to the DUT so a longer stress test is possible.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +    yield RisingEdge(clk)
Not sure why you are waiting for a falling and a rising edge here.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +    while(fifo_rdcnt != channel_number * read_items | dut.fifo_out_valid.value.integer):
This is kinda confusing to read, and I guess you meant to use a logical 'or' as the last operator? The single '|' is a bitwise or, and that's probably not what you want here.

2018-08-02 08:09 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +   input [CHANN-1:0]        fifo_rd_en_channel,
For the interface to the channels, please use I/O names that correspond with the glip interface (FWFT FIFOs), i.e. 'data', 'ready', and 'valid'. Maybe something like 'fifo_in_valid_channel', or 'channel_fifo_in_valid'...

2018-08-06 09:43 UTC, yaorong0921 commented on src/common/logic/channel_multiplexing/cocotb/channel_demultiplexer_test.py
> +    yield write_thread.join()
Thank you for all of your comments! 
I am working on the new test when read and write threads work simultaneously.

2018-08-06 09:55 UTC, yaorong0921 commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +            fifo_rdcnt += 1
yes, I need to reset the "fifo_rd_en_channel" for the current channel, before I changed to the next channel.

2018-08-06 09:56 UTC, yaorong0921 commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +    yield RisingEdge(clk)
This comes also from "waiting untill all the signals stable"

2018-08-06 10:14 UTC, yaorong0921 commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +            fifo_rdcnt += 1
and also reset the 'fifo_rd_rst_channel'.

2018-08-06 10:21 UTC, yaorong0921 commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +   input [CHANN-1:0]        fifo_rd_en_channel,
If I understand correctly, we should see each channel fifo also as small GLIP interface. 

So
in demultiplexer (ingress):  'fifo_rd_en_channel' --> 'fifo_out_valid_channel' 
                                                'fifo_dout_channel' --> 'fifo_out_data_channel'

in multiplexer (egress)    : 'fifo_wr_en_chanel' --> 'fifo_in_valid_channel' 
                                             : 'fifo_din_channel' --> 'fifo_in_data_channel'

2018-08-09 17:18 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +   input [CHANN-1:0]        fifo_rd_en_channel,
Exactly, the channel interface should resemble the GLIP interface. So in this case here the 'fifo_rd_en_channel' should become 'fifo_in_ready_channel' and instead of a 'fifo_empty_channel' you should have a 'fifo_in_valid_channel'. Otherwise we would have to change the interface of whatever modules we want to use in the design depending on whether or not we want to use channel multiplexing. Also, read and write enable signals are commonly used with standard FIFOs which have a different timing behaviour. Hence, this naming is misleading here.

2018-08-28 14:24 UTC, koenenwmn requested changes
As discussed, especially the wrapper module needs some changes. For the other changes, we can have a look at them together tomorrow if this would help you.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/top_channel_multiplexing.sv
> +   input [CHANN-1:0]        fifo_rd_clk_channel,
In general, the modules won't have different clocks for reading and writing. Hence, there should only be a 'fifo_clk_channel' which is connected to the read and write clocks of the submodule.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/top_channel_multiplexing.sv
> + * This module transmits data from PC back.
As discussed, this is not the purpose of this module! The module should be a wrapper for the demultiplexer and multiplexer module so that other modules of a design interface a single module, just like with the glip toplevel.
You could then write a loop-back test in cocotb.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/top_channel_multiplexing_test.py
> +    dut._log.info("First test done")
Please always add a newline at the end of the file.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +         nxt_channel_number <= 0;
No need to reset this here as it should be set in the combinatoric part.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
>        fifo_wr_en_channel = {(CHANN-1){1'b0}};
Here is where you should set nxt_channel_number:
`nxt_channel_number = channel_number;`

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +         current_fifo_in_ready <= 0;
Some issues here. 1.: if you set this signal here in the synchronous part you should not set it in the combinatoric part and vice versa. 2.: you should stick to the same naming as with the other signals, e.i. `fifo_in_ready` & `nxt_fifo_in_ready`. 3.: you don't actually need this signal at all and you should avoid the output register for `fifo_in_ready` as it adds a one cycle delay. Instead it would be preferable to assign the inverted full flag of the selected channel directly:
`assign fifo_in_ready = fifo_full_channel[channel_number];`
You can do the same with the output registers in the multiplexer module.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/top_channel_multiplexing_test.py
> +"""
As discussed, this test will need some rework for the updated wrapper module.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/cocotb/channel_multiplexing_common.py
> +        dut.fifo_in_ready_channel[channel_count] <= 0
Regarding these 'for' loops (the other one further up), are you purposely waiting for 6 cycles of the same clock? If so please explain in a comment.

2018-08-28 14:24 UTC, koenenwmn commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +   logic [7:0] nxt_channel_number;
Somewhere it should explain in a comment why/that the maximal possible number of channels is hardcoded to 256.

2018-08-29 11:52 UTC, yaorong0921 commented on src/common/logic/channel_multiplexing/verilog/channel_demultiplexer.sv
> +         current_fifo_in_ready <= 0;
Thanks for all your comments. I changed demultiplexer as you said. And for multiplexer, because I would like to get the fifo_out_data and fifo_out_valid at Risingedge to make all clear. So I used the naming as `nxt_fifo_out_data` and `nxt_fifo_out_valid`.

2018-08-30 15:00 UTC, koenenwmn commented
Thanks again for the work @yaorong0921 !
As discussed, I will continue the work to also implement the software side and then merge everything together.

2018-08-30 15:00 UTC, closed without merging